#!/bin/bash

# options
export EDITOR=code
export SHELL=/opt/homebrew/bin/zsh
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$XDG_CONFIG_HOME"/local/share
export XDG_CACHE_HOME="$XDG_CONFIG_HOME"/cache
export XDG_STATE_HOME="$XDG_CONFIG_HOME"/local/state
export XDG_DESKTOP_DIR="$HOME"/Desktop
export XDG_DOWNLOAD_DIR="$HOME"/Downloads
export XDG_PUBLICSHARE_DIR="$HOME"/Public
export XDG_DOCUMENTS_DIR="$HOME"/Documents
export XDG_MUSIC_DIR="$HOME"/Music
export XDG_PICTURES_DIR="$HOME"/Pictures
export XDG_VIDEOS_DIR="$HOME"/Movies
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export ZSH_CACHE_DIR="$XDG_CACHE_HOME"/zsh
export ZSH="$XDG_CONFIG_HOME"/local/oh-my-zsh
export HOMEBREW_NO_ANALYTICS=true
export HOMEBREW_NO_INSTALL_CLEANUP=true
export MYVIMRC="$XDG_CONFIG_HOME"/vim/vimrc
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME"/npm
export YARN_CACHE_FOLDER="$XDG_CACHE_HOME"/yarn
export SVN_HOME="$XDG_CONFIG_HOME"/subversion
export WAKATIME_HOME="$XDG_CONFIG_HOME"/wakatime
export TERMINFO="$XDG_CONFIG_HOME"/terminfo
export _Z_DATA="$ZDOTDIR"/.z
export LESSHISTFILE=-
