# One Dark

[colors.primary]
background = '#21242a'
foreground = '#acb1bd'

[colors.normal]
black   = '#21242a'
red     = '#d17277'
green   = '#a0c180'
yellow  = '#dfc184'
blue    = '#73ade9'
magenta = '#bb7bd7'
cyan    = '#6fb3bf'
white   = '#acb1bd'

[colors.bright]
black   = '#21242a'
red     = '#d17277'
green   = '#a0c180'
yellow  = '#dfc184'
blue    = '#73ade9'
magenta = '#bb7bd7'
cyan    = '#6fb3bf'
white   = '#acb1bd'

# [colors.dim]
# black = "#131415"
# red = "#864343"
# green = "#777c44"
# yellow = "#9e824c"
# blue = "#556a7d"
# magenta = "#75617b"
# cyan = "#5b7d78"
# white = "#828482"

# [colors.hints]
# start = { foreground = "#1d1f21", background = "#e9ff5e" }
# end = { foreground = "#e9ff5e", background = "#1d1f21" }

# [colors.search]
# matches = { foreground = "#000000", background = "#ffffff" }
# focused_match = { foreground = "#ffffff", background = "#000000" }
