#!/usr/bin/env zsh

# system executables
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec

# local system binaries
export PATH=/usr/local/sbin:/usr/local/bin:$PATH

# my paths
export PATH=$PATH:${DOTFILES}/bin

# homebrew path
eval "$(/opt/homebrew/bin/brew shellenv)"

# lua path
export PATH=$HOME/.local/share/lua/bin:$PATH

# go path
export PATH=$PATH:$GO_PATH/bin
export PATH=$PATH:$GOROOT/bin

# conda
export PATH="/opt/homebrew/anaconda3/bin:$PATH"

# java path
export PATH="/opt/homebrew/opt/openjdk@17/bin:$PATH"

# jaro mail
export PATH=/Applications/JaroMail.app/Contents/Resources/jaro/bin:$PATH

# add zsh-completions to fpath
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.omz}/custom}/plugins/zsh-completions/src

# global yarn bin
export PATH="$HOME/.yarn/bin:$PATH"

# global go bin
export PATH="$HOME/.go/bin:$PATH"

# php
export PATH="/opt/homebrew/opt/php/bin:/$PATH"

# nvm and completions
[[ -f "/opt/homebrew/opt/nvm/nvm.sh" ]] && . "/opt/homebrew/opt/nvm/nvm.sh"
[[ -f "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ]] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# macos paths
for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

# clear duplicates
typeset -gU fpath path

# set the path for macos
[[ -x /bin/launchctl ]] && /bin/launchctl setenv PATH $PATH
