#!/usr/bin/env zsh

# system executables
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec
    
# local system binaries
export PATH=/usr/local/sbin:/usr/local/bin:$PATH

# dotfiles bin
export PATH=$PATH:${DOTFILES}/bin

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# go path
export PATH=$PATH:$GO_PATH/bin
export PATH=$PATH:$GOROOT/bin

# add zsh-completions to fpath
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.omz}/custom}/plugins/zsh-completions/src

# nvm and completions
[[ -f "/opt/homebrew/opt/nvm/nvm.sh" ]] && . "/opt/homebrew/opt/nvm/nvm.sh"
[[ -f "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ]] && . "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# macos paths
for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

# clear duplicates
typeset -gU fpath path

# set the path for macos
[[ -x /bin/launchctl ]] && /bin/launchctl setenv PATH $PATH
