#!/usr/bin/env zsh

# system executables -> path
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec:$PATH"

# local system binaries -> path
export PATH="/usr/local/bin:/usr/local/sbin:/usr/local/MacGPG2/libexec:$PATH"

# homebrew -> shell
eval "$(/opt/homebrew/bin/brew shellenv)"

# dotfiles bin -> path
export PATH="$DOTFILES/bin:$PATH"

# go -> path
export PATH="$GO_PATH/bin:$PATH"
export PATH="$GOROOT/bin:$PATH"

# go bin -> path
export PATH="$HOME/.config/go/bin:$PATH"

# java -> path
export PATH="$PATH:/opt/homebrew/opt/openjdk/bin"

# lm studio -> path
export PATH="$PATH:$HOME/.lmstudio/bin"

# spicetify -> path
export PATH="$PATH:$HOME/.spicetify"

# osx-zsh-completions
fpath=($HOME/.dotfiles/plugins/zsh-completions/src/ $fpath)
autoload -Uz compinit
compinit -d $HOME/.cache/zsh/zcompdump

# macos paths -> path
for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

# clear duplicate paths
typeset -gU fpath path

# set the path for macos
[[ -x /bin/launchctl ]] && /bin/launchctl setenv PATH $PATH