#!/usr/bin/env zsh

skip_global_compinit=1

export DOTFILES=$HOME/.dotfiles

# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_DATA_HOME="$HOME/.local/share"
# export XDG_STATE_HOME="$HOME/.local/state"
# export XDG_CACHE_HOME="$HOME/.cache"

export EDITOR="nvim"
export VISUAL="codium"
export PAGER="less"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export LESSHISTFILE="-"
export GPG_TTY=$(tty)

export ZSH="$HOME/.omz"
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

export HOMEBREW_NO_INSTALL_CLEANUP=true
export HOMEBREW_BUNDLE_FILE_GLOBAL="$DOTFILES/macos/brewfile"
export HOMEBREW_NO_ANALYTICS=true
export HOMEBREW_NO_ENV_HINTS=true

# export AWS_HOME="$XDG_CONFIG_HOME/aws"
# export AWS_ECR_CACHE_DIR="$XDG_CACHE_HOME/ecr"

export NVM_HOMEBREW="/opt/homebrew/opt/nvm"

export GOPATH="${HOME}/.go"
export GOBIN="${HOME}/.go/bin"
export GOROOT="/opt/homebrew/opt/go/libexec"

export CURL_HOME="${DOTFILES}/config/curl"
export WGETRC="${DOTFILES}/config/wget/wgetrc"
export INPUTRC="${DOTFILES}/config/readline/inputrc"

export GENCOMPL_FPATH="$HOME/.omz/completions"

export BAT_CONFIG_PATH="$HOME/.dotfiles/config/bat/config"

# export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
# export RUSTUP_HOME="$XDG_CONFIG_HOME/rust"

# export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
# export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/config"
# export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"

# export PNPM_HOME="$XDG_DATA_HOME/pnpm"

# export BUN_INSTALL="$XDG_CONFIG_HOME/bun"

# export DENO_INSTALL="$XDG_CONFIG_HOME/deno"

# export YARN_CACHE_FOLDER="$XDG_CACHE_HOME/yarn"

# export FLY_CONFIG_DIR="$XDG_CONFIG_HOME/fly"

# export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"

# export WAKATIME_HOME="$XDG_CONFIG_HOME/wakatime"

export OP_BIOMETRIC_UNLOCK_ENABLED=true
export SSH_AUTH_SOCK="$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock"

export TIMEFMT=$'\n================\nCPU\t%P\nuser\t%*U\nsystem\t%*S\ntotal\t%*E'
