#!/usr/bin/env zsh

skip_global_compinit=1

setopt noglobalrcs

export ZSH="$HOME/.omz"
export DOTFILES=$HOME/.dotfiles

export GOPATH="${HOME}/.go"
export GOROOT="/opt/homebrew/opt/go/libexec"
export CARGO_HOME="${HOME}/.cargo"
export PYENV_ROOT="$HOME/.pyenv"
export HOMEBREW_NO_ENV_HINTS=true
export TMUX_PLUGIN_MANAGER_PATH="${HOME}/.tmux/plugins"
export CURL_HOME="${DOTFILES}/config/curl"
export WGETRC="${DOTFILES}/config/wget/wgetrc"
export OP_BIOMETRIC_UNLOCK_ENABLED=true
export SSH_AUTH_SOCK="$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock"
export LESSHISTFILE="-"

export EDITOR='nvim'
export VISUAL='nvim'
export BROWSER="open"
export LANG='en_US.UTF-8'
export PAGER='less'