#!/usr/bin/env zsh

setopt noglobalrcs

export DOTFILES=$HOME/.dotfiles

export EDITOR="ghostty nvim"
export VISUAL="codium"
export BROWSER="Twilight"
export PAGER="less -RF"
export LESSHISTFILE="-"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export GPG_TTY=$TTY

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LOCALE=en_US.UTF-8

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export HOMEBREW_BAT=1
export HOMEBREW_FORCE_BREWED_CURL=1
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_BUNDLE_FILE_GLOBAL="$DOTFILES/macos/brewfile"

export CURL_HOME="$DOTFILES/config/curl"
export WGETRC="$DOTFILES/config/wget/wgetrc"
export BAT_CONFIG_PATH="$DOTFILES/config/bat/config"

export GOPATH="$HOME/.config/go"
export GOBIN="$HOME/.config/go/bin"
export GOROOT="/opt/homebrew/opt/go/libexec"
export GOTELEMETRY="off"

export AWS_HOME="$HOME/.config/aws"
export CARGO_HOME="$HOME/.config/cargo"
export RUSTUP_HOME="$HOME/.config/rust"
export FLY_CONFIG_DIR="$HOME/.config/fly"
export PNPM_HOME="$HOME/.config/pnpm"

export CONDA_ENVS_PATH="$HOME/.config/miniconda3/envs"

export ZSH_CACHE_DIR="$HOME/.cache/zsh"
export NPM_CONFIG_CACHE="$HOME/.cache/npm"
export YARN_CACHE_FOLDER="$HOME/.cache/yarn"

export TRANSMISSION_WEB_HOME=""
export OP_BIOMETRIC_UNLOCK_ENABLED=true
export SSH_AUTH_SOCK="$HOME/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock"

export TIMEFMT=$'%J \n================\n CPU\t%P\nuser\t%*U\nsystem\t%*S\ntotal\t%*E'