#!/usr/bin/env zsh

# p10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# run p10k configure
[[ ! -f ${HOME}/.cache/p10k.zsh ]] || source ${HOME}/.cache/p10k.zsh

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  brew
  nvm
  golang
  1password-op
  zsh-autosuggestions
  zsh-syntax-highlighting
  zsh-history-substring-search
)

# source oh-my-zsh.
source $ZSH/oh-my-zsh.sh

# zsh files
source ${DOTFILES}/zsh/settings.zsh
source ${DOTFILES}/zsh/aliases.zsh

# start ssh
eval "$(ssh-agent -s)" > /dev/null 2>&1
# ssh-add ~/.ssh/id_ed25519 > /dev/null 2>&1

# rust
[[ ! -f $HOME/.cargo/env ]] || . $HOME/.cargo/env

# fzf
if [ $(command -v fzf) ]; then
  source $DOTFILES/config/fzf/fzf.zsh
fi

# pyenv
if [[ -d "$PYENV_ROOT" ]] && \
  command -v pyenv >/dev/null 2>&1 && \
  command -v pyenv-virtualenv-init >/dev/null; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# iterm2 integration
[[ -f "${DOTFILES}/config/iterm/iterm.zsh" ]] && . "${DOTFILES}/config/iterm/iterm.zsh"

# opam ocaml
[[ ! -r '/Users/dany/.opam/opam-init/init.zsh' ]] || source '/Users/dany/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null

# used with magick rock
export DYLD_FALLBACK_LIBRARY_PATH="$(brew --prefix)/lib:$DYLD_FALLBACK_LIBRARY_PATH"

# load completions
autoload -Uz compinit
if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
  compinit
else
  compinit -C
fi

# fastdetch
# fastfetch
