#!/usr/bin/env zsh

# skips compinit
skip_global_compinit=1

# 
autoload -U compaudit compinit zrecompile

# prompt
source ${DOTFILES}/zsh/prompt.zsh

# plugins
source ${DOTFILES}/tools/zsh-completions/zsh-completions.plugin.zsh
source ${DOTFILES}/tools/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${DOTFILES}/tools/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source ${DOTFILES}/tools/zsh-history-substring-search/zsh-history-substring-search.zsh

# zsh files
source ${DOTFILES}/zsh/settings.zsh
source ${DOTFILES}/zsh/aliases.zsh

# start ssh-agent
eval "$(ssh-agent -s)" > /dev/null 2>&1

# fzf
if [ $(command -v fzf) ]; then
  source $DOTFILES/config/fzf/fzf.zsh
fi

# conda
source $DOTFILES/config/conda/conda.zsh
