#!/usr/bin/env python
import urllib.parse
import json
import subprocess
import argparse
import tempfile
import os
import re
import random
import sys
from config import *
import requests
# Set this to False if you want LIBREX_INSTANCE to be used.
RANDOM_INSTANCE = True
# To find more instances go to:
# https://github.com/hnhx/librex/#instances
LIBREX_INSTANCE = "https://search.davidovski.xyz/"

def get_arguments():
    parser = argparse.ArgumentParser(description='fzf-librex')
    parser.add_argument('-s', '--search', type=str, metavar='TEXT', help='Search the internet (text)', nargs='+')
    parser.add_argument('-i', '--image', type=str, metavar='TEXT', help='Search for images', nargs='+')
    parser.add_argument('-t', '--torrent', type=str, metavar='TEXT', help='Search various torrent websites.', nargs='+')
    parser.add_argument('-v', '--video', type=str, metavar='TEXT', help='Search for videos', nargs='+')
    parser.add_argument('-l', '--list', action="store_true", default=False, help='List librex instances.')
    return parser.parse_args()


def list_instances():
    # OLD METHOD
    #md = requests.get("https://raw.githubusercontent.com/hnhx/librex/main/README.md").text
    #links = re.findall("^| \[.+?\]\((.*?)\)", md)[1:][:-1]
    #working = []
    #for link in links:
    #    if not link.endswith(("onion/","i2p/")):
    #        working.append(link)
    json_stuff = requests.get("https://raw.githubusercontent.com/hnhx/librex/main/instances.json").json()
    working = []
    for instance in json_stuff["instances"]:
        if instance["clearnet"] != None:
            working.append(instance["clearnet"])
    return working
    

def get_random_instance():
    url_list = list_instances()
    while len(url_list) > 0:
        random_index = random.randint(0, len(url_list))-1
        url = url_list.pop(random_index)
        status_code = requests.get(url).status_code
        if status_code == 200:
            break
    return url

def api(search_text, search_type):
    search_type = str(search_type)
    search_text = ' '.join(search_text)
    if RANDOM_INSTANCE == False:
        instance = LIBREX_INSTANCE
    elif RANDOM_INSTANCE == True:
        instance = get_random_instance()
        print(f"Using random instance: {instance}")
    search_url = urllib.parse.urljoin(instance,f"/api.php?q={urllib.parse.quote(search_text)}&t={search_type}")
    data = requests.get(search_url).json()
    return data

def fzf(search, type_, opener):
    type_ = str(type_)
    data = api(search, type_)
    file = tempfile.TemporaryFile().name
    sep = " | "
    with open(file,"a",encoding="utf-8") as f:
        for i, result in enumerate(data):
            if "special_response" in result:
                pass
            elif type_ == "0" or type_ == "2":
                f.write(f'{i} {result["title"]}{sep}{result["url"]}\n')
            elif type_ == "1":
                f.write(f'{i} {result["alt"]}{sep}{result["url"]}\n')
            elif type_ == "3":
                f.write(f'{i} ({result["source"]}) {result["size"]} [S:{result["leechers"]}, L:{result["seeders"]}] {result["name"]}\n')
    with open(file, "r", encoding="utf-8") as f:
        text = '\n'.join(f.read().splitlines()[:-1])

    choice = subprocess.getoutput(f"fzf --reverse < {file}")
    os.remove(file)
    if choice != "":
        feed = {
            "0": "url",
            "1": "thumbnail",
            "2": "url",
            "3": "magnet",
        }
        num = int(choice.split(" ")[0])
        url = data[num][feed[type_]]
        if type_ == "3" and "=" in url:
            url = url.split("=")[1]
        subprocess.Popen([opener, url])

def main():
    args = get_arguments()
    if len(sys.argv) == 1:
        print("No arguments were given. Read the help (-h/--help).")
        sys.exit(1)
    if args.search:
        fzf(args.search, 0, BROWSER)
    elif args.image:
        fzf(args.image, 1, IMAGE)
    elif args.video:
        fzf(args.video, 2, PLAYER)
    elif args.torrent:
        fzf(args.torrent, 3, TORRENT)
    elif args.list:
        print('\n'.join(list_instances()))

if __name__ == "__main__":
    main()
