#!/usr/bin/env python
import os
import subprocess
import sys
from config import *

# Going to assume this script is with all the other fzf-scripts.
SCRIPTS_DIR = os.path.dirname(sys.argv[0])
SCRIPTS_NAMES = os.listdir(SCRIPTS_DIR)
SCRIPTS_NAMES = list(set(SCRIPTS_NAMES) - set(["config.py", "__pycache__", "fzf-hub", "fzf-librex"]))

def main():
    with open("scripts.txt", "w") as f:
        f.write('\n'.join(SCRIPTS_NAMES))

    choice = subprocess.getoutput(FZF.replace("FILE","scripts.txt"))
    os.remove("scripts.txt")
    if choice != "":
        text = open(os.path.join(SCRIPTS_DIR, choice), "r").readline()
        # This will probably work best and only with python and if it
        # has #!/usr/bin/env <runner> at the top
        if text.startswith("#!/usr/bin/env"):
            runner = text.split(" ")[1].splitlines()[0]
            os.system(f"{runner} {os.path.join(SCRIPTS_DIR, choice)}")
        else:
            print("ERROR: #!/usr/bin/env <lang> not at the top of the file")
            
        sys.exit(0)

if __name__ == "__main__":
    main()
