#!/usr/bin/env python
import subprocess
import os
import platform
from config import *

def main():
    if platform.system() == "Windows":
        appdata = os.getenv('APPDATA')
        configs =\
f"""alacritty - {appdata}\\alacritty\\alacritty.yml
emacs - {appdata}\\.emacs.d\\init.el
mpv - {appdata}\\mpv\\mpv.conf
qutebrowser - {appdata}\\qutebrowser\\config\\config.py
"""

    with open("configs.txt","w") as f:
        f.write(configs)

    choice = subprocess.getoutput(FZF.replace("FILE","configs.txt"))
    os.remove("configs.txt")
    if choice != "":
        subprocess.Popen([EDITOR, choice.split(' - ')[1]])

if __name__ == "__main__":
    main()
