cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'autoenv'
brew 'coreutils'
brew 'fnm'
brew 'go'
brew 'gh'
brew 'mongocli'
brew 'node'
brew 'ranger'
brew 'wget'
brew 'yarn'
brew 'yt-dlp/taps/yt-dlp'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

cask 'iterm2'
cask 'mongodb-compass'
cask 'visual-studio-code'
