#!/usr/bin/env bash

set -e

# exec &> >(tee -a "$HOME"/.dotfiles/install.log)

STEPS_ENVIORNMENT="steps/enviornment.yml"
STEPS_BREW_FORMULA="steps/brew-formula.yml"
STEPS_BREW_CASKS="steps/brew-casks.yml"

DOTBOT_DIR="plugins/dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

run_dotbot() {
  local config
  config="$1"

  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    --plugin-dir plugins/dotbot-brewfile \
    -c "${config}" "${@}"
}

run_dotbot $STEPS_ENVIORNMENT
# run_dotbot $STEPS_BREW_FORMULA
# run_dotbot $STEPS_BREW_CASKS
