#!/usr/bin/env bash

# only 0xAARRGGBB color arguments supported

options=(
	style=rounded
	width=3.0
	hidpi=on
	active_color=0xc0FF00F2
	inactive_color=0xc00080FF
	ax_focus=off
)

borders "${options[@]}"

# blur_radius=160.0
# 0xff76cce0
# 0xff414550
# 0xffdad2d2
# 0xc0FF00F2 0xFFAC34a6
# 0xFF0080FF 0xFF29639E
# gradient(top_left=0xc0FF00F2,bottom_right=0xFF0080FF)
# gradient(top_right=0xFF0080FF,bottom_left=0xc0FF00F2)
# glow(0xc0FF00F2)
