#!/usr/bin/env bash

# only 0xAARRGGBB color arguments supported

options=(
	style=rounded
	width=4
	hidpi=on
	active_color=0xc0ff00f2
	inactive_color=0xff0080ff
	ax_focus=off
    blur_radius=160.0
)

borders "${options[@]}"

# background_color=0xff414550
# 0xff76cce0
# 0xff414550
# 0xc0ff00f2
# 0xff0080ff
# 0xffdad2d2