#!/bin/bash

# navigate spaces
lcmd - 1 : yabai -m space --focus 1
lcmd - 2 : yabai -m space --focus 2
lcmd - 3 : yabai -m space --focus 3
lcmd - 4 : yabai -m space --focus 4
lcmd - 5 : yabai -m space --focus 5

# navigate spaces
hyper - 1 : yabai -m space --focus web
hyper - 2 : yabai -m space --focus ide
hyper - 3 : yabai -m space --focus dev

# move window to workspace and focus it
lctrl - 1 : yabai -m window --space 1 --focus
lctrl - 2 : yabai -m window --space 2 --focus
lctrl - 3 : yabai -m window --space 3 --focus
lctrl - 4 : yabai -m window --space 4 --focus
lctrl - 5 : yabai -m window --space 5 --focus

# moving windows inside a workspace
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# navigate bsp windows inside a workspace
lctrl + alt - h : yabai -m window --focus west
lctrl + alt - j : yabai -m window --focus south
lctrl + alt - k : yabai -m window --focus north
lctrl + alt - l : yabai -m window --focus east

# navigate stacked windows
lalt - m : yabai -m window --focus stack.next
lalt - n : yabai -m window --focus stack.prev

# toggle split direction
lalt - e : yabai -m window --toggle split

# change layout of desktop
lctrl + alt - b : yabai -m space --layout bsp
lctrl + alt - s : yabai -m space --layout stack
lctrl + alt - f : yabai -m space --layout float

# toggle zoom
lalt - d : yabai -m window --toggle zoom-parent
lalt - f : yabai -m window --toggle zoom-fullscreen

# resize windows
lalt - h : yabai -m window --resize left:-32:0; \
  yabai -m window --resize right:-32:0
lalt - j : yabai -m window --resize bottom:0:32; \
  yabai -m window --resize top:0:32
lalt - k : yabai -m window --resize top:0:-32; \
  yabai -m window --resize bottom:0:-32
lalt - l : yabai -m window --resize right:32:0; \
  yabai -m window --resize left:32:0

# app scripts
hyper - c : ./$HOME/.dotfiles/bin/yabai-codium
hyper - f : ./$HOME/.dotfiles/bin/yabai-finder
hyper - x : ./$HOME/.dotfiles/bin/yabai-ghostty

# app commands
hyper - a : open -a Apps.app
hyper - b : open -a "Brave Browser.app"
hyper - m : open -a Mail.app
hyper - n : open -a Notes.app
hyper - z : open -a Twilight.app

# adjust rounded corners
# hyper - s : sharpener on -r 1

# restart
hyper - r : \
    skhd --restart-service; \
    yabai --restart-service;
