#!/usr/bin/env bash

# moving windows
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# move focus container to workspacee
alt - 1 : yabai -m window --space 1 --focus
alt - 2 : yabai -m window --space 2 --focus
alt - 3 : yabai -m window --space 3 --focus
alt - 1 : yabai -m window --space 4 --focus
alt - 2 : yabai -m window --space 5 --focus

# set insertion point for focused container
shift + lctrl + alt - h : yabai -m window --insert west
shift + lctrl + alt - j : yabai -m window --insert south
shift + lctrl + alt - k : yabai -m window --insert north
shift + lctrl + alt - l : yabai -m window --insert east

# navigate workspaces
cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3

# navigate bsp windows
lctrl + alt - h : yabai -m window --focus west
lctrl + alt - j : yabai -m window --focus south
lctrl + alt - k : yabai -m window --focus north
lctrl + alt - l : yabai -m window --focus east

# navigate stacked windows
lctrl + alt - m : yabai -m window --focus stack.next
lctrl + alt - n : yabai -m window --focus stack.prev

# rotate on x and y axis
lctrl + alt - x : yabai -m space --mirror x-axis
lctrl + alt - y : yabai -m space --mirror y-axis

# toggle split direction
lalt - e : yabai -m window --toggle split

# change layout of desktop
lctrl + alt - b : yabai -m space --layout stack
lctrl + alt - s : yabai -m space --layout bsp

# toggle zoom
lalt - d : yabai -m window --toggle zoom-parent
lalt - f : yabai -m window --toggle zoom-fullscreen

# toggle float
lctrl + shift + alt - space : yabai -m window --toggle float

# toggle sticky
lctrl + alt - space : yabai -m window --toggle sticky

# resize based on defined grid.        r:c:x:y:w:h
# lctrl - up    : yabai -m window --grid 2:2:1:2:2:3
# lctrl - down  : yabai -m window --grid 5:5:4:0:1:1
# lctrl - left  : yabai -m window --grid 1:2:0:0:1:1
# lctrl - right : yabai -m window --grid 1:2:1:0:1:1

# equalize size of windows
lctrl + alt - e : yabai -m space --balance

# toggle gap or padding
lctrl + alt - g : yabai -m space --toggle gap
lctrl + alt - p : yabai -m space --toggle padding

# toggle topmost
alt - o : yabai -m window --toggle topmost

# toggle sticky to pip
alt - p : yabai -m window --toggle sticky
yabai -m window --toggle topmost
yabai -m window --grid 5:5:4:0:1:1

# resize windows
lalt - h : yabai -m window --resize left:12: \
  yabai -m window --resize right:-12:0
lalt - j : yabai -m window --resize bottom:0:12 \
  yabai -m window --resize top:0:12

lalt - k : yabai -m window --resize top:0:-12 \
  yabai -m window --resize bottom:0:-12
lalt - l : yabai -m window --resize right:12:0 \
  yabai -m window --resize left:12:0

# change layout of desktop
lctrl + alt - b : yabai -m space --layout stack
lctrl + alt - s : yabai -m space --layout bsp

# open apps
hyper - z : open -a "/Applications/Ghostty.app"
hyper - b : open -a "/Applications/Brave Browser.app"
hyper - c : open -a "/Applications/VSCodium.app"
hyper - q : open -a "/Applications/qutebrowser.app"
hyper - n : open -a "/Applications/Notes.app"

# restart all wm services
hyper - r : \
  osascript -e \
  "display notification \"Restarting all Services\" with title \"Yabai\"" \
  skhd --stop-service \
  skhd --start-service \
  yabai --stop-service \
  yabai --start-service

printf '%s' "$(date '+%F %T%z') yabai configuration loaded...\\n"