#!/usr/bin/env bash

# moving windows inside a workspace
shift + alt - h : yabai -m window --warp west
shift + alt - j : yabai -m window --warp south
shift + alt - k : yabai -m window --warp north
shift + alt - l : yabai -m window --warp east

# move window to workspace and focus it
# alt - 1 : yabai -m window --space 1 --focus
# alt - 2 : yabai -m window --space 2 --focus
# alt - 3 : yabai -m window --space 3 --focus
# alt - 4 : yabai -m window --space 4 --focus
# alt - 5 : yabai -m window --space 5 --focus

# navigate workspaces
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5

# navigate bsp windows inside a workspace
lctrl + alt - h : yabai -m window --focus west
lctrl + alt - j : yabai -m window --focus south
lctrl + alt - k : yabai -m window --focus north
lctrl + alt - l : yabai -m window --focus east

# navigate stacked windows
alt - m : yabai -m window --focus stack.next
alt - n : yabai -m window --focus stack.prev

# rotate on x and y axis
alt - x : yabai -m space --mirror x-axis
alt - y : yabai -m space --mirror y-axis

# toggle split direction
lalt - e : yabai -m window --toggle split

# change layout of desktop
lctrl + alt - b : yabai -m space --layout bsp
lctrl + alt - s : yabai -m space --layout stack
lctrl + alt - f : yabai -m space --layout float

# toggle zoom
lalt - d : yabai -m window --toggle zoom-parent
lalt - f : yabai -m window --toggle zoom-fullscreen

# toggle float
lctrl + shift + alt - space : yabai -m window --toggle float

# toggle sticky
lctrl + alt - space : yabai -m window --toggle sticky

# resize based on defined grid.        r:c:x:y:w:h
# lctrl - up    : yabai -m window --grid 2:2:1:2:2:3
# lctrl - down  : yabai -m window --grid 5:5:4:0:1:1
# lctrl - left  : yabai -m window --grid 1:2:0:0:1:1
# lctrl - right : yabai -m window --grid 1:2:1:0:1:1

# equalize size of windows
lctrl + alt - e : yabai -m space --balance

# toggle gap or padding
lctrl + alt - g : yabai -m space --toggle gap
lctrl + alt - p : yabai -m space --toggle padding

# toggle topmost
alt - o : yabai -m window --toggle topmost

# toggle sticky to pip
alt - p : yabai -m window --toggle sticky; \
  yabai -m window --toggle topmost; \
  yabai -m window --grid 5:5:4:0:1:1

# resize windows
lalt - h : yabai -m window --resize left:-32:0; \
  yabai -m window --resize right:-32:0
lalt - j : yabai -m window --resize bottom:0:32; \
  yabai -m window --resize top:0:32
lalt - k : yabai -m window --resize top:0:-32; \
  yabai -m window --resize bottom:0:-32
lalt - l : yabai -m window --resize right:32:0; \
  yabai -m window --resize left:32:0

# open apps
hyper - x : open -a Ghostty.app
hyper - z : open -a Twilight.app
hyper - b : open -a "Brave Browser.app"
hyper - c : open -a VSCodium.app
hyper - d : open -a Discord.app
hyper - f : ./$HOME/.dotfiles/config/yabai/scripts/switch-apps.sh
hyper - m : open -a Mail.app
hyper - n : open -a Notes.app
hyper - a : open -a "Activity Monitor.app"
hyper - p : open -a Launchpad.app

hyper - r : \
  skhd --restart-service; \
  yabai --restart-service;

# brew services restart borders;
# brew services restart svim;


