tap "1password/tap"
tap "aws/tap"
tap "felixkratz/formulae"
tap "koekeishiya/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "moritzsternemann/apple-fonts"
tap "oven-sh/bun"
tap "stripe/stripe-cli"

# Official Amazon AWS command-line interface
brew "awscli"
# Curl like simplicity to access AWS resources
brew "awscurl"
# Record your work in a terminal
brew "asciinema"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# A cat clone with syntax highlighting and Git integration
brew "bat"
# Extensions to bat
brew "bat-extras"
# A package manager
brew "bun"
# View pictures in your terminal
brew "chafa"
# GNU internationalization (i18n) and localization (l10n) library
brew "gettext"
# Core application library for C
brew "glib"
# Statistics utility to count lines of code
brew "cloc"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Good-lookin' diffs with diff-highlight and more
brew "diff-so-fancy"
# Load and unload env variables on the current directory
brew "direnv"
# Utility that lets you work with Fly.io
brew "flyctl"
# GNU Ubiquitous Intelligent Language for Extensions
brew "guile"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# Subtitle renderer for the ASS/SSA subtitle format
brew "libass"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Collection of GNU find, xargs, and locate
brew "findutils"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Cleans up old and inactive forks on your GitHub account
brew "fork-cleaner"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU awk utility
brew "gawk"
# Geometry Engine
brew "geos"
# GitHub command-line tool
brew "gh"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# A system monitoring tool
brew "glances"
# GNU version of the tar archiving utility
brew "gnu-tar"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Colorize logfiles and command output
brew "grc"
# Interactive process viewer
brew "htop"
# Add GitHub support to git on the command-line
brew "hub"
# Command-line benchmarking tool
brew "hyperfine"
# Utility to optimize JPEG files
brew "jpegoptim"
# Lightweight and flexible command-line JSON processor
brew "jq"
# YAML Parser
brew "libyaml"
# Scripting language
brew "lua"
# Package manager for Lua modules
brew "luarocks"
# Command line interface for the Mac App Store
brew "mas"
# Library for a binary-based efficient data interchange format
brew "msgpack"
# 'traceroute' and 'ping' in a single tool
brew "mtr"
# NCurses Disk Usage
brew "ncdu"
# Vim-based text editor
brew "neovim"
# Command-line system information tool
brew "neofetch"
# HTTP/2 C Library
brew "nghttp2"
# Port scanning utility for large networks
brew "nmap"
# Node.js
brew "node"
# Command-line utility for retrieving currently playing media
brew "nowplaying-cli"
# Development kit for the Java programming language
brew "openjdk@11"
# Apache Parquet command-line tools and utilities
brew "parquet-tools"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# PNG image optimizing utility
brew "pngquant"
# A package manager
brew "pnpm"
# Show ps output as a tree
brew "pstree"
# A package manager
brew "pyenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# A highly customizable macOS status bar replacement
brew "sketchybar"
# Keyboard-driven window manager
brew "koekeishiya/formulae/skhd"
# Change the audio source for Mac OS X from the command line
brew "switchaudio-osx"
# User interface to the TELNET protocol
brew "telnet"
# Simplified manual pages
brew "tldr"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Vi 'workalike' with many additional features
brew "vim"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Internet file retriever
brew "wget"
# Command-line audio/video downloader
brew "yt-dlp"
# Linter for YAML files
brew "yamllint"
# General-purpose lossless data-compression library
brew "zlib"
# AWS SAM CLI 🐿 is a tool for local development and testing of Serverless applications
brew "aws/tap/aws-sam-cli"
# Stripe CLI utility
brew "stripe/stripe-cli/stripe"
# Yabai is a tiling window manager for macOS
brew "koekeishiya/formulae/yabai"
# A package manager
brew "yarn"
# Apple symbols
cask "sf-symbols"
# Brings 1Password to your terminal
cask "1password-cli"
# The App That Opens Apps
cask "apparency"
# Web browser
cask "brave-browser"
# Web browser
cask "google-chrome"
# Free and open-source media player
cask "iina"
# Terminal emulator
cask "kitty"
# Finder Toolbar app for macOS
cask "openinterminal"
# Tool for working with MongoDB
cask "mongodb-compass"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organized
cask "notion"
# API platform for building and using API
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Application for inspecting installer packages
cask "suspicious-package"
# Bittorrent client
cask "transmission"
# Open source cross-platform multimedia playe
cask "vlc"
# General-purpose text editor
cask "textmate"
# Open-source code editor
cask "visual-studio-code"
# Terminal with AI and collaborative tools
cask "warp"
# Video communication and virtual meeting platform
cask "zoom"
