#!/usr/bin/env bash

echo " > Creating folders in $HOME/.config/..."
mkdir -p "$HOME/.config/git" && echo " > Created $HOME/.config/git"
mkdir -p "$HOME/.config/zsh" && echo " > Created $HOME/.config/zsh"
mkdir -p "$HOME/.config/op" && echo " > Created $HOME/.config/op"

echo " > Copying config files to $HOME/.config/..."
cp -r "$DOTFILES/config/bat" "$HOME/.config/" && echo " > Copied $DOTFILES/config/bat"
cp -r "$DOTFILES/config/curl" "$HOME/.config/" && echo " > Copied $DOTFILES/config/curl"
cp -r "$DOTFILES/config/git/dot.gitconfig" "$HOME/.config/git/config" && echo " > Copied $DOTFILES/config/git/config"
cp -r "$DOTFILES/config/htop" "$HOME/.config/" && echo " > Copied $DOTFILES/config/htop"
cp -r "$DOTFILES/config/karabiner" "$HOME/.config/" && echo " > Copied $DOTFILES/config/karabiner"
cp -r "$DOTFILES/config/kitty" "$HOME/.config/" && echo " > Copied $DOTFILES/config/kitty"
cp -r "$DOTFILES/config/neofetch" "$HOME/.config/" && echo " > Copied $DOTFILES/config/neofetch"
cp -r "$DOTFILES/config/ngrok" "$HOME/.config/" && echo " > Copied $DOTFILES/config/ngrok"
cp -r "$DOTFILES/config/npm" "$HOME/.config/" && echo " > Copied $DOTFILES/config/npm"
cp -r "$DOTFILES/config/ranger" "$HOME/.config/" && echo " > Copied $DOTFILES/config/ranger"
cp -r "$DOTFILES/config/skhd" "$HOME/.config/" && echo " > Copied $DOTFILES/config/skhd"
cp -r "$DOTFILES/config/ssh" "$HOME/.ssh/" && echo " > Copied $DOTFILES/config/ssh"
cp -r "$DOTFILES/config/vim" "$HOME/.config/" && echo " > Copied $DOTFILES/config/vim"
cp -r "$DOTFILES/config/wget" "$HOME/.config/" && echo " > Copied $DOTFILES/config/wget"
cp -r "$DOTFILES/config/yabai" "$HOME/.config/" && echo " > Copied $DOTFILES/config/yabai"
cp -p "$DOTFILES/shell/.zshrc" "$HOME" && echo " > Copied $DOTFILES/shell/.zshrc"
cp -p "$DOTFILES/shell/.zprofile" "$HOME" && echo " > Copied $DOTFILES/shell/.zprofile"
