# yt-dlp Configuration File

# External Downloader Arguments (aria2c)
downloader_args="-c -j 4 -x 4 -s 4 -k 2M"

# Log File Path
log_file="/Users/stache/yt-dlp.log"

# Retry Mechanism
retry_count=3
retry_backoff=5

# Subtitle Preferences
sub_lang="en"
write_sub=true

# Encrypted Cookie Directory
COOKIEDIR="/Users/stache/.config/yt-dlp/cookies"

# Encrypted Cookie File Path
cookie_file="/cookies.txt.gpg"
