#!/usr/bin/env bash

# configs for all apps
yabai -m rule --add app=".*" sub-layer=normal

# above apps
sub_layer_above=(
  System Settings
  System Information
  System Preferences
)

for ((i = 1; i <= "${#sub_layer_above[@]}"; i++)); do
  yabai -m rule --add label="unmanage_${sub_layer_above[(($i - 1))]}" app="^${sub_layer_above[(($i - 1))]}.*$" sub-layer=above
done

# floating apps
unmanaged=(
  1Password
  Archive Utility
  Calculator
  ChatGPT
  Contacts
  Dictionary
  Downie 4
  FaceTime
  Finder
  FINAL FANTASY XIV
  FINAL FANTASY XIV ONLINE
  GPG Keychain
  IINA
  iPhone Mirroring
  Karabiner-Elements
  Karabiner-MultitouchExtension
  Keka
  Messages
  mpv
  Notes
  Permute 3
  Photo Booth
  Preferences
  Quicktime Player
  Reminders
  Source
  Software Update
  Stickies
  Suspicious Package
  System Settings
  System Preferences
  System Information
  VLC
  VMware Fusion
)

for ((i = 1; i <= "${#unmanaged[@]}"; i++)); do
  yabai -m rule --add label="unmanage_${unmanaged[(($i - 1))]}" app="^${unmanaged[(($i - 1))]}.*$" manage=off
done

# space 1
SPACE1=(
  Calendar
  Mail
  Steam
  NVIDIA GeForce NOW
  FINAL FANTASY XIV
)

for ((i = 1; i <= "${#SPACE1[@]}"; i++)); do
  yabai -m rule --add label="space1_${SPACE1[(($i - 1))]}" app="^${SPACE1[(($i - 1))]}.*$" space=^1
done

# space 2
SPACE2=(
  Twilight
  Zen
  Safari
)

for ((i = 1; i <= "${#SPACE2[@]}"; i++)); do
  yabai -m rule --add label="space2_${SPACE2[(($i - 1))]}" app="^${SPACE2[(($i - 1))]}.*$" space=^2
done

# space 3
SPACE3=(
  Ghostty
  VSCodium
  Postman
  Docker Desktop
  Xcode
)

for ((i = 1; i <= "${#SPACE3[@]}"; i++)); do
  yabai -m rule --add label="space3_${SPACE3[(($i - 1))]}" app="^${SPACE3[(($i - 1))]}.*$" space=^3
done

# space 4
SPACE4=(
  Brave Browser
  Tor Browser
)

for ((i = 1; i <= "${#SPACE4[@]}"; i++)); do
  yabai -m rule --add label="space4_${SPACE4[(($i - 1))]}" app="^${SPACE4[(($i - 1))]}.*$" space=^4
done

yabai -m config --space 2 layout stack
