#!/usr/bin/env bash

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
  layout stack \
  external_bar all:0:0 \
  top_padding 3 \
  bottom_padding 3 \
  left_padding 3 \
  right_padding 3 \
  window_gap 3 \
  window_origin_display default \
  window_placement second_child \
  split_ratio 0.50 \
  auto_balance off \
  window_zoom_persist on \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  mouse_follows_focus off \
  focus_follows_mouse off

# window_shadow float

# rules for all apps
yabai -m rule --add app=".*" sub-layer=normal

# rules for specific apps
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Bluetooth Inspector$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^ChatGPT$" manage=off
yabai -m rule --add app="^choose$" manage=off
yabai -m rule --add app="^Contacts$" manage=off
yabai -m rule --add app="^DevTools$" manage=off
yabai -m rule --add app="^Downie 4$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^EdgeView$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Find My$" manage=off
yabai -m rule --add app="^GPG Keychain$" manage=off
yabai -m rule --add app="^iPhone Mirroring$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-MultitouchExtension$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^Manage WireGaurd Tunnels$" manage=off
yabai -m rule --add app="^Mpv$" manage=off
yabai -m rule --add app="^mpv$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^Permute 3$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^RiseupVPN$" manage=off
yabai -m rule --add app="^Source$" manage=off
yabai -m rule --add app="^Suspicious Package$" manage=off
yabai -m rule --add app="^Shortcuts$" manage=off
yabai -m rule --add app="^Software Update$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off sub-layer=above
yabai -m rule --add app="^System Preferences$" manage=off sub-layer=above
yabai -m rule --add app="^Transmission$" manage=off
yabai -m rule --add app="^UTM$" manage=off
yabai -m rule --add app="^Vesktop$" manage=off
yabai -m rule --add app="^VLC$" manage=off
yabai -m rule --add app="^WireGaurd$" manage=off

# fix for borderless qutebrowser
yabai -m rule --add app="^qutebrowser$" title!="^$" role="AXWindow" subrole="AXDialog" manage=on

# sketchybar events
yabai -m signal --add event=window_focused action="sketchybar -m --trigger window_focus &> /dev/null"
yabai -m signal --add event=window_title_changed action="sketchybar -m --trigger title_change &> /dev/null"

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=space_changed action="yabai -m window --focus $(yabai -m query --windows --window | jq ".id")"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
