#!/usr/bin/env bash

# load yabi as sudo
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# define sketchybar
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus &> /dev/null"
# yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change &> /dev/null"
# yabai -m signal --add event=window_created action="sketchybar --trigger space_windows_change" label="sketchybarNewWindowCreated"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger space_windows_change" label="sketchybarWindowDestroyed"

# sketchybar
# yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
# yabai -m signal --add event=application_front_switched action="sketchybar --trigger title_change"
# yabai -m signal --add event=window_focused action="sketchybar --trigger title_change"
# yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change" active=yes

# float small, non-resizable windows
# yabai -m signal --add event=window_created action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float" label="floatSmallWindows"


BAR_HEIGHT=0 # $(sketchybar -m --query bar | jq -r '.height')

GENERAL=(
    external_bar all:"${BAR_HEIGHT}":0
    split_type auto
    split_ratio 0.5
    auto_balance off
    insert_feedback_color 0xff282a36
)

LAYOUT=(
    layout bsp
    top_padding 6
    bottom_padding 6
    left_padding 6
    right_padding 6
    window_gap 6
)

WINDOWS=(
    window_placement second_child
    window_shadow float
    window_opacity off
    active_window_opacity 1.0
    normal_window_opacity 0.97
    window_opacity_duration 0.15
    window_animation_duration 0.0
    window_origin_display default
    window_zoom_persist on
)

MOUSE=(
    mouse_modifier fn
    mouse_action1 move
    mouse_action2 resize
    mouse_drop_action swap
    focus_follows_mouse off
    mouse_follows_focus off
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${MOUSE[@]}"

# use apprc file
source "${HOME}/.config/yabai/apprc"

# apply rules to existing windows
yabai -m rule --apply

echo "yabai configuration loaded.."
