#!/usr/bin/env zsh

# skips compinit
skip_global_compinit=1

#
# ZSH_DISABLE_COMPFIX="true"

# zsh completions
source ${DOTFILES}/plugins/zsh-completions/zsh-completions.plugin.zsh

# completions
autoload -Uz compaudit compinit zrecompile

# prompt
source ${DOTFILES}/shell/config/prompt.zsh

# plugins
source ${DOTFILES}/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${DOTFILES}/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source ${DOTFILES}/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# zsh files
source ${DOTFILES}/shell/config/settings.zsh
source ${DOTFILES}/shell/config/aliases.zsh

# start ssh-agent
eval "$(ssh-agent -s)" >/dev/null 2>&1

# rust
source "/Users/stache/.config/cargo/env"

# conda
source "/opt/miniconda3/etc/profile.d/conda.sh"

# nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# fzf defaults
source /opt/homebrew/opt/fzf/shell/completion.zsh
source /opt/homebrew/opt/fzf/shell/key-bindings.zsh

# fzf use :: instead of **
export FZF_COMPLETION_TRIGGER='::'

# fzf defaults
export FZF_DEFAULT_OPTS="--layout=reverse --border --prompt='> ' --walker-skip=.git,node_modules,target,Library,Pictures,Documents,Movies,Music,.Trash --tmux=60% --no-info --no-scrollbar --no-hscroll --margin=0 --padding=0 --bind='ctrl-space:toggle' --bind='ctrl-o:toggle-preview' --bind='ctrl-s:toggle-sort' --bind='ctrl-y:execute-silent(echo {+} | pbcopy)' --bind='ctrl-e:execute(codium {+})' --bind='ctrl-n:execute(nvim {+})'"

# fzf files
export FZF_ALT_C_OPTS="--header='Files' --walker=file --preview='bat -n --color=always {}' --bind='enter:execute(nvim {} +1)'"

# fzf folders
export FZF_CTRL_T_OPTS="--header='Directories' --walker=dir,hidden,follow --preview='tree -C {} | head -200' --bind='enter:execute(nvim {})+abort'"

# zoxide
eval "$(zoxide init bash)"
