#!/usr/bin/env zsh

# skips compinit
skip_global_compinit=1

# zsh completions
source ${DOTFILES}/plugins/zsh-completions/zsh-completions.plugin.zsh

# completions
autoload -Uz compaudit compinit zrecompile

# prompt
source ${DOTFILES}/shell/config/prompt.zsh

# plugins
source ${DOTFILES}/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${DOTFILES}/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source ${DOTFILES}/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh

# zsh files
source ${DOTFILES}/shell/config/settings.zsh
source ${DOTFILES}/shell/config/aliases.zsh

# start ssh-agent
eval "$(ssh-agent -s)" >/dev/null 2>&1

# nvm
export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# rust
. "/Users/stache/.config/cargo/env"

# fzf
source /opt/homebrew/opt/fzf/shell/completion.zsh
source /opt/homebrew/opt/fzf/shell/key-bindings.zsh

# fzf base options
export FZF_DEFAULT_OPTS="--height=60% --layout=reverse --prompt='> ' --walker-skip=.git,node_modules,target,Library,Pictures,Documents,Movies,Music,.Trash --tmux=center --no-info --no-scrollbar --no-hscroll --margin=0 --padding=0 --bind='ctrl-space:toggle' --bind='ctrl-o:toggle-preview' --bind='ctrl-s:toggle-sort' --bind='ctrl-y:execute-silent(echo {+} | pbcopy)' --bind='ctrl-e:execute(codium {+})' --bind='ctrl-n:execute(nvim {+})'"

# fzf dir search
export FZF_CTRL_T_OPTS="--header='Directories' --walker=dir,hidden,follow --preview='tree -C {} | head -200' --bind='enter:execute(nvim {})+abort'"

# fzf file search
export FZF_ALT_C_OPTS="--header='Files' --walker=file --preview='bat -n --color=always {}' --bind='enter:execute(nvim {} +1)'"

# zoxide
eval "$(zoxide init zsh)"

# conda
if [ -f "/Users/stache/.config/miniconda3/etc/profile.d/conda.sh" ]; then
  . "/Users/stache/.config/miniconda3/etc/profile.d/conda.sh"
fi

