# vim:ft=kitty

# theme ----------------------------------------

include theme.conf

# fonts -----------------------------------------

font_family       FiraCode Nerd Font Regular
bold_font         FiraCode Nerd Font Regular
italic_font       FiraCode Nerd Font Regular
bold_italic_font  FiraCode Nerd Font Regular

# font_family       Cascadia Mono PL Regular
# bold_font         Cascadia Mono PL Regular
# italic_font       Cascadia Mono PL Regular
# bold_italic_font  Cascadia Mono PL Regular

# font_family       SauceCodePro Nerd Font Regular
# bold_font         SauceCodePro Nerd Font Regular
# italic_font       SauceCodePro Nerd Font Regular
# bold_italic_font  SauceCodePro Nerd Font Regular

font_size                  14.0

# modify_font cell_width   0px
# modify_font cell_height  0px

# text_composition_strategy  1.0 70
text_fg_override_threshold 0

# advanced -------------------------------------

enable_audio_bell          no
scrollback_lines           1000000
editor                     /opt/homebrew/bin/nvim

# windows ---------------------------------------

background_opacity       1.0
window_border_width      1pt
window_padding_width     4
draw_minimal_borders     yes
hide_window_decorations  titlebar-only

# macos ----------------------------------------

macos_option_as_alt           yes
macos_titlebar_color          dark
macos_traditional_fullscreen  yes

# tabs -----------------------------------------

tab_bar_style          powerline
tab_powerline_style    angled
tab_bar_margin_height  4.0 3.0
tab_bar_margin_width   4.0
active_tab_font_style  normal

# keybindings ---------------------------------

map kitty_mod+l      next_layout
map kitty_mod+enter  launch --cwd=current

