# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{

#: MensloLGS NF {{{
#: https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized
#: https://github.com/shaunsingh

font_family      MensloLGS NF Regular
italic_font      MensloLGS NF Regular Italic
bold_font        MensloLGS NF Bold
bold_italic_font MensloLGS NF Bold Italic

font_size 13.0
modify_font cell_height 0px

#: }}}

#: Operator Mono {{{
#: https://www.typography.com/fonts/operator/styles/operatormono
#: https://github.com/kiliman/operator-mono-lig

# font_family      Operator Mono SSm Lig Book
# italic_font      Operator Mono SSm Lig Book Italic
# bold_font        Operator Mono SSm Lig Bold
# bold_italic_font Operator Mono SSm Lig Bold Italic

# font_size 13.0
# modify_font cell_height 0px

#: }}}

# : MonoLisa {{{
# : https://www.monolisa.dev

# font_family      MonoLisa Custom Regular
# italic_font      MonoLisa Custom Regular Italic
# bold_font        MonoLisa Custom Bold
# bold_italic_font MonoLisa Custom Bold Italic

# font_size 13.0
# modify_font cell_height 0px

# : }}}

#: }}}

#: Scrollback {{{

scrollback_lines 10000000

#: }}}

#: Mouse {{{

url_color #0087bd
url_style curly

#: }}}

#: Terminal bell {{{

enable_audio_bell no

#: }}}

#: Window layout {{{

enabled_layouts *
window_border_width 0.1pt
draw_minimal_borders  yes
window_padding_width  10
active_border_color   #05ce0f
inactive_borser_color #323232
remember_window_size  yes
initial_window_width  80
initial_window_height 30

#: }}}

#: Advanced {{{

startup_session ./startup.conf

#: }}}

#: OS specific tweaks {{{

wayland_titlebar_color       dark
macos_titlebar_color         dark 
macos_option_as_alt          yes
macos_traditional_fullscreen yes 

#: }}}

#: Window management {{{

map ctrl+alt+enter  launch --cwd=current

#: }}}

#: Window Navigation {{{

map cmd+q no_op
map cmd+w no_op
map ctrl+alt+j neighboring_window down
map ctrl+alt+k neighboring_window up
map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right

#: }}}

#: Layout management {{{

map ctrl+alt+f goto_layout fat
map ctrl+alt+s goto_layout stack
map ctrl+alt+t goto_layout tall
map ctrl+alt+p last_used_layout
map ctrl+alt+z toggle_layout stack

#: }}}

#: Unicode Symbol Maps {{{

# include unicodes.conf

#: }}}

#: Color scheme {{{

background_opacity 1
include snazzy.conf

#: }}}

#: Keyboard Shortcuts{{{

# copy to clipboard
map kitty_mod+c copy_to_clipboard
map cmd+c copy_to_clipboard

# paste from clipboard
map kitty_mod+v paste_from_clipboard
map cmd+v paste_from_clipboard

# use cmd+k to clear the terminal
map cmd+k clear_terminal to_cursor active

# map kitty_mod+f11 toggle_fullscreen
map ctrl+cmd+f toggle_fullscreen

# map kitty_mod+f5 load_config_file
map ctrl+cmd+, load_config_file

#: }}}

#: Miscellaneous{{{

# map open kitty website
map shift+cmd+/ open_url https://sw.kovidgoyal.net/kitty/ 🍎

#: }}}
