# vim:ft=kitty

include ~/.dotfiles/config/kitty/onedark_pro.conf

# fonts -----------------------------------------

# font_family       CaskaydiaCove Nerd Font Propo SemiBold
# bold_font         CaskaydiaCove Nerd Font Propo Bold
# italic_font       CaskaydiaCove Nerd Font Propo SemiBold Italic
# bold_italic_font  CaskaydiaCove Nerd Font Propo Bold Italic

font_family       FiraCode Nerd Font SemiBold
bold_font         FiraCode Nerd Font Bold
italic_font       FiraCode Nerd Font SemiBold Italic
bold_italic_font  FiraCode Nerd Font Bold Italic

font_size                 14

# modify_font cell_width    1.2px
# modify_font cell_height   6px

modify_font underline_position 1.2px

# text_composition_strategy legacy

# disable_ligatures         always

# advanced -------------------------------------

enable_audio_bell          no
scrollback_lines           1000000
editor                     /opt/homebrew/bin/nvim

# windows ---------------------------------------

window_border_width      4
window_padding_width     0
draw_minimal_borders     yes
hide_window_decorations  titlebar-only

# macos ----------------------------------------

macos_option_as_alt           yes
macos_titlebar_color          dark
macos_traditional_fullscreen  yes

# tabs -----------------------------------------

tab_bar_style          powerline
tab_powerline_style    angled
# tab_bar_margin_height  4.0 3.0
# tab_bar_margin_width   4.0
active_tab_font_style  normal

# keybindings ---------------------------------

map kitty_mod+l      next_layout
map kitty_mod+enter  launch --cwd=current

