#!/usr/bin/env bash

# open apps
# hyper - z : open -a /Applications/iTerm.app
# hyper - x : open "/Applications/VSCodium.app"
# hyper - c : alacritty --
# hyper - v : open -a /Applications/kitty.app
# hyper - b : open -a "Brave Browser.app"
# hyper - n : open -a "Finder.app"

# toggle kitty
# alt - 0x32 : ~/.dotfiles/config/skhd/scripts/kitty.sh
