version: 1
git_protocol: ssh
editor: codium
prompt: enabled
prefer_editor_prompt: enabled
pager: delta
aliases:
    co: pr checkout
http_unix_socket:
browser: /Applications/Zen.app/Contents/MacOS/zen
