# https://github.com/dlvhdr/gh-dash#%EF%B8%8F-configuring
prSections:
  # - title: My Pull Requests
  #   filters: is:open author:@me
  #   type: null
  # - title: Needs My Review
  #   filters: is:open review-requested:@me
  #   type: null
  # - title: Involved
  #   filters: is:open involves:@me -author:@me
  #   type: null
  - title: Mine
    filters: sort:updated-desc is:pr is:open archived:false user:@me
  - title: Dependabot
    filters: is:open -org:einride review-requested:@me author:app/dependabot archived:false
  - title: Created @einride
    filters: is:open author:@me org:einride archived:false
  - title: Review requested @einride
    filters: is:open review-requested:@me -author:app/dependabot org:einride archived:false
  - title: Dependabot @einride
    filters: is:open org:einride review-requested:@me author:app/dependabot archived:false
issuesSections:
  # - title: My Issues
  #   filters: is:open author:@me
  # - title: Assigned
  #   filters: is:open assignee:@me
  # - title: Involved
  #   filters: is:open involves:@me -author:@me
  - title: Mine
    filters: sort:updated-desc is:issue is:open archived:false user:@me
  - title: Created
    filters: sort:updated-desc is:open is:issue archived:false author:danydodson
  - title: Assigned
    filters: sort:updated-desc is:open is:issue archived:false assignee:danydodson
  - title: Mentioned
    filters: sort:updated-desc is:open is:issue archived:false mentions:danydodson
  - title: Involved
    filters: sort:updated-desc is:issue is:open archived:false involves:@me
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs: []
  branches: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
