#!/bin/zsh

export DOTFILES="${HOME}"/.dotfiles

source "${DOTFILES}"/shell/functions.sh
source "${DOTFILES}"/shell/exports.sh
source "${DOTFILES}"/zsh/prompt.zsh
source "${DOTFILES}"/shell/paths.sh
source "${DOTFILES}"/zsh/plugins.zsh
source "${DOTFILES}"/zsh/history.zsh
source "${DOTFILES}"/zsh/settings.zsh
source "${DOTFILES}"/zsh/comps.zsh
source "${DOTFILES}"/shell/aliases.sh
