#!/usr/bin/env bash

# shellcheck disable=SC1091
source "/Users/dany/.dotfiles/config/sketchybar/colors.sh"
source "/Users/dany/.dotfiles/config/sketchybar/icons.sh"

ITEM_DIR="/Users/dany/.dotfiles/config/sketchybar/items"
PLUGIN_DIR="/Users/dany/.dotfiles/config/sketchybar/plugins"

ICON_FONT="Hack Nerd Font"
LABEL_FONT="SF Pro"

##### Bar Appearance #####
sketchybar --bar height=30 \
                 position=top \
                 corner_radius=0 \
                 y_offset=2 \
                 blur_radius=70 \
                 padding_left=0 \
                 padding_right=6 \
                 margin=3 \
                 color="$TRANS_BLACK" \
                 shadow=off

############## GLOBAL DEFAULTS ##############
sketchybar --default updates=when_shown \
                     icon.color="$WHITE" \
                     icon.highlight_color="$PINK" \
                     label.color="$WHITE" \
                     background.corner_radius=0 \
                     background.height=30

sketchybar --add item logo left \
           --set logo icon= \
                 icon.padding_left=10 \
                 icon.padding_right=10 \
                 background.padding_right=4 \
                 background.padding_left=4 \
                 click_script="sketchybar --update"

##### Adding Mission Control Space Indicators #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
SPACES=()

for i in "${!SPACE_ICONS[@]}"
do
  sid=$((i+1))
  SPACES+=(space."$sid")
  sketchybar --add space space.$sid left \
             --set space.$sid associated_space=$sid \
                              icon="${SPACE_ICONS[i]}" \
                              icon.padding_left=20 \
                              icon.padding_right=20 \
                              icon.highlight_color="$PINK" \
                              background.padding_left=-4 \
                              background.padding_right=-4 \
                              background.drawing=on \
                              label.drawing=off \
                              click_script="yabai -m space --focus $sid"
done

##### Changing Defaults #####
sketchybar --default updates=when_shown \
                     padding_left=5 \
                     padding_right=5 \
                     icon.font="$ICON_FONT:Regular:15.0" \
                     label.font="$LABEL_FONT:Medium:12.0" \
                     icon.color="$WHITE" \
                     label.color="$WHITE" \
                     icon.padding_left=4 \
                     icon.padding_right=4 \
                     label.padding_left=4 \
                     label.padding_right=4

##### Adding Left Items #####
# sketchybar --add item space_separator left \
#            --set space_separator icon= \
#                                  background.padding_left=23 \
#                                  background.padding_right=23 \
#                                  label.drawing=off \
#                                  icon.color="$WHITE"

sketchybar --add item window_title left \
           --set window_title script="$PLUGIN_DIR/window_title.sh" \
                              icon.drawing=off \
                              label.color="$WHITE" \
                              label.font="$LABEL_FONT:Heavy:13.0" \
           --subscribe window_title front_app_switched

##### Adding Center Items #####
sketchybar --add item spot_logo center \
           --set spot_logo icon= \
                           label.drawing=off \
                           icon.color="$GREEN" \

sketchybar --add item spot center \
           --set spot update_freq=1 \
                      icon.drawing=off \
                      updates=on \
                      script="$PLUGIN_DIR/spotifyIndicator.sh" \
                      background.padding_left=0

##### Adding Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

echo "sketchybar configuration loaded..."

# https://felixkratz.github.io/SketchyBar/config/events
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
# https://felixkratz.github.io/SketchyBar/config/items
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item