#!/usr/bin/env bash

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

source "$CONFIG_DIR/styles.sh"

POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"
POPUP_OFF="sketchybar --set \$NAME popup.drawing=off"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

# unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

sketchybar --bar "${bar[@]}" \
           --default "${item_defaults[@]}"


source "$ITEM_DIR/spaces_simple.sh"

# source "$ITEM_DIR/datetime.sh"
# source "$ITEM_DIR/dnd.sh"
source "$ITEM_DIR/wifi.sh"
# source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
# source "$ITEM_DIR/diskmonitor.sh"

source "$ITEM_DIR/spacer.sh" 2 right

# source "$ITEM_DIR/brew.sh" right
# source "$ITEM_DIR/reminders.sh" right
# source "$ITEM_DIR/messages.sh" right
# source "$ITEM_DIR/mail.sh" right
# source "$ITEM_DIR/weather.sh" right
# source "$ITEM_DIR/stress.sh" right

# source "$ITEM_DIR/transmission.sh"
# source "$ITEM_DIR/music.sh"

source "$ITEM_DIR/spacer.sh" 4 right

source "$ITEM_DIR/yabai.sh"

sketchybar --add bracket left.side '/space\..*/' \
           --set left.side "${bracket_defaults[@]}" \
           \
           --add bracket notifications weather aqi reminders messages mail brew \
           --set notifications "${bracket_defaults[@]}" \
           \
           --add bracket status_icons diskmonitor volume_icon volume wifi dnd date clock battery \
           --set status_icons "${bracket_defaults[@]}"
           
# ##### Bar Appearance #####
# sketchybar --bar height=28 \
#                  position=top \
#                  corner_radius=0 \
#                  notch_width=188 \
#                  y_offset=2 \
#                  blur_radius=70 \
#                  padding_left=0 \
#                  padding_right=6 \
#                  margin=3 \
#                  color="$BAR_COLOR_TRANSPARENT" \
#                  shadow=off

# ############## GLOBAL DEFAULTS ##############
# sketchybar --default updates=when_shown \
#                      icon.color="$ICON_COLOR" \
#                      icon.highlight_color="$HIGHLIGHT" \
#                      label.color="$LABEL_COLOR" \
#                      background.corner_radius=0 \
#                      background.height=26

# sketchybar --add item logo left \
#            --set logo icon= \
#                  icon.padding_left=10 \
#                  icon.padding_right=10 \
#                  background.padding_right=4 \
#                  background.padding_left=4 \
#                  click_script="sketchybar --update"

# ##### Changing Defaults #####
# sketchybar --default updates=when_shown \
#                      padding_left=5 \
#                      padding_right=5 \
#                      icon.font="$ICON_FONT:Regular:15.0" \
#                      label.font="$LABEL_FONT:Medium:12.0" \
#                      icon.color="$ICON_COLOR" \
#                      label.color="$LABEL_COLOR" \
#                      icon.padding_left=4 \
#                      icon.padding_right=4 \
#                      label.padding_left=4 \
#                      label.padding_right=4

# ##### Adding Mission Control Space Indicators #####
# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# SPACES=()

# for i in "${!SPACE_ICONS[@]}"
# do
#   sid=$((i+1))
#   SPACES+=(space."$sid")
#   sketchybar --add space space.$sid left \
#              --set space.$sid associated_space=$sid \
#                               icon="${SPACE_ICONS[i]}" \
#                               icon.padding_left=20 \
#                               icon.padding_right=20 \
#                               icon.highlight_color="$HIGHLIGHT" \
#                               background.padding_left=-4 \
#                               background.padding_right=-4 \
#                               background.drawing=on \
#                               label.drawing=off \
#                               click_script="yabai -m space --focus $sid"
# done

# ##### Adding Left Items #####
# source "$ITEM_DIR/yabai.sh"

# sketchybar --add item space_separator left \
#            --set space_separator icon= \
#                                  background.padding_left=10 \
#                                  background.padding_right=23 \
#                                  label.drawing=off \
#                                  icon.color="$ICON_COLOR"

# sketchybar --add item front_app left \
#            --set front_app \
#                  background.color="$TRANSPARENT" \
#                  background.padding_left=0 \
#                  background.padding_right=0 \
#                  icon.y_offset=1 \
#                  icon.color="$ICON_COLOR" \
#                  label.drawing=no \
#                  script="$PLUGIN_DIR/front_app.sh" \
#            --add item front_app.name left \
#            --set front_app.name \
#                  background.color="$TRANS" \
#                  background.padding_right=0 \
#                  icon.drawing=off \
#                  label.font="$LABEL_FONT:Heavy:12.0" \
#                  label.drawing=yes

# sketchybar --add bracket front_app_bracket \
#                  front_app \
#                  front_app.separator \
#                  front_app.name \
#            --subscribe front_app front_app_switched

# ##### Adding Center Items #####
# sketchybar --add event spotify_change "$SPOTIFY_EVENT" \
#     --add item spotify e \
#     --set spotify \
#           icon= \
#           icon.y_offset=1 \
#           icon.font="$ICON_FONT:Regular:20.0" \
#           label.drawing=off \
#           label.padding_left=3 \
#           script="$PLUGIN_DIR/spotify.sh" \
#     --subscribe spotify spotify_change mouse.clicked

# ##### Adding Right Items #####
# sketchybar --add item clock right \
#            --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload on
sketchybar --update
sketchybar --trigger space_change

echo "sketchybar configuration loaded..."
