"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# open-shell-here
[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

# close after 1 esc
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

# quicklook
[[manager.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"'
'''

# chmod
[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

# sudo-demo
[[manager.prepend_keymap]]
on  = "<C-t>"
run = "plugin sudo-demo"

# hide-preview
[[manager.prepend_keymap]]
on = "T"
run = "plugin --@sync hide-preview"
desc = "Hide or show preview"

# boydaihungst/file-extra-metadata
[[manager.prepend_keymap]]
on = "<Tab>"
run = "spot"
desc = "Spot hovered file"