"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "tokyonight-night"

[manager]
cwd = { fg = "cyan" }
hovered = { reversed = true }
preview_hovered = { underline = false }
border_style = { fg = "gray"}

[which]
cols = 3
separator = " 󰁔 "
separator_style = { fg = "#4b32c3" }

# [filetype]
# rules = [
  # orphan symbolic links
  # { name = "*", is = "orphan", fg = "red", bg = "#22262f" },
# ]
