"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
# ratio = [1, 5, 4]
show_symlink = false
show_hidden = true

[[plugin.prepend_fetchers]]
id   = "mime"
if   = "!mime"
name = "*"
run  = "mime-ext"
prio = "high"

[[plugin.prepend_previewers]]
name = "*.csv"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.md"
run = "rich-preview"

[[plugin.prepend_previewers]]
mime = "application/bittorrent"
run = "torrent-preview"
