"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [2, 3, 4]
show_symlink = true
show_hidden = true

[preview]
wrap = "no"
max_width = 1200
max_height = 1200

# yazi-rs/plugins:mime-ext
[[plugin.prepend_fetchers]]
id = "mime"
name = "*"
run = "mime-ext"
prio = "high"

# boydaihungst/file-extra-metadata
[[plugin.append_spotters]]
name = "*"
run = "file-extra-metadata"
[[plugin.append_previewers]]
name = "*/"
run = "folder"
sync = true
[[plugin.append_previewers]]
name = "text/*"
run = "codium"
[[plugin.append_previewers]]
name = "*"
run = "file-extra-metadata"

# AnirudhG07/rich-preview
[[plugin.prepend_previewers]]
name = "*.csv"
run = "rich-preview"
[[plugin.prepend_previewers]]
name = "*.md"
run = "rich-preview"

# kirasok/torrent-preview.yazi.git
[[plugin.prepend_previewers]]
mime = "application/bittorrent"
run = "torrent-preview"

# Sonico98/exifaudio.yazi.git
[[plugin.prepend_previewers]]
mime = "audio/*"
run = "exifaudio"

# yazi-rs/plugins:lsar
[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run = "lsar"
[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run = "lsar"
