"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [ 2, 3, 4 ]
sort_by = "alphabetical"
sort_dir_first = true
show_hidden = true
show_symlink = false
# scrolloff = 100

[preview]
wrap = "no"
tab_size = 4
image_filter = "catmull-rom"
image_quality = 90

[opener]
edit = [ { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" } ]
open = [ { run = 'xdg-open "$1"', desc = "Open", for = "linux" }, { run = 'open "$@"', desc = "Open", for = "macos" } ]
reveal = [ { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" }, { run = 'open -R "$1"', desc = "Reveal", for = "macos" }, { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" } ]
extract = [ { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" } ]
play = [ { run = 'mpv --force-window "$@"', orphan = true, for = "unix" }, { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" } ]

[open]
rules = [
  { name = "*/", use = [ "edit", "open", "reveal" ] },
  { mime = "text/*", use = [ "edit", "reveal" ] },
  { mime = "image/*", use = [ "open", "reveal" ] },
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  { mime = "application/{,g}zip", use = [ "extract", "reveal" ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },
  { mime = "application/{json,x-ndjson}", use = [ "edit", "reveal" ] },
  { mime = "*/javascript", use = [ "edit", "reveal" ] },
  { mime = "inode/x-empty", use = [ "edit", "reveal" ] },
  { name = "*", use = [ "open", "reveal" ] },
]

[plugin]
prepend_fetchers = [
  { id = "mime", name = "*", run = "mime", if = "!mime", prio = "high" },
]

prepend_spotters = [
  { name = "*", run = "file-extra-metadata" },
]

prepend_previewers = [
  { name = "*/", run = "folder", sync = true },
  { mime = "text/*", run = "code" },
  { mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },
  { mime = "application/{json,x-ndjson}", run = "json" },
  { mime = "text/csv", run = "miller" },
  { mime = "application/bittorrent", run = "torrent-preview" },
  { mime = "audio/*", run = "exifaudio" },
  { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
  { mime = "image/*", run = "image" },
  { mime = "video/*", run = "video" },
  { mime = "application/pdf", run = "pdf" },
  { mime = "application/{,g}zip", run = "lsar" },
  { mime = "application/{x-tar,bzip*,7z-compressed,xz,rar,iso9660-image}", run = "lsar" },
  { mime = "font/*", run = "font" },
  { mime = "application/vnd.ms-opentype", run = "font" },
  { mime = "inode/x-empty", run = "empty" },
  { name = "*", run = "file-extra-metadata" },
]

prepend_preloaders = [
  { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
  { mime = "image/*", run = "image" },
  { mime = "video/*", run = "video" },
  { mime = "application/pdf", run = "pdf" },
  { mime = "font/*", run = "font" },
  { mime = "application/vnd.ms-opentype", run = "font" },
]

[input]
cursor_blink = false
