[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/.dotfiles/config/tmux"
startup_command = "v tmux.conf"
preview_command = "bat --color=always ~/.dotfiles/config/tmux/tmux.conf"

[[session]]
name = "sesh config"
path = "~/.dotfiles/config/sesh"
startup_command = "v sesh.toml"
preview_command = "bat --color=always ~/.dotfiles/config/sesh/sesh.toml"

[[session]]
name = "neovim keymaps"
path = "~/.dotfiles/config/nvim/lua/config"
startup_command = "v keymaps.lua"
preview_command = "bat --color=always ~/.dotfiles/config/nvim/lua/config/keymaps.lua"
