name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://Secrets/ry6onrjrmsodnzopqalaw7xdkm/secrets/secret_note

      - name: Print masked secret
        run: echo Secret "${{ steps.op-load-secret.outputs.SECRET }}"

