name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Shell check
        uses: rafaeleyng/shellcheck-action@v2
        with:
          command: ./scripts/tools/check.sh

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://Secrets/i2selwuyepehl4yrfetwl5zxri/secrets/secret_one

      - name: Print masked secret
        run: echo Secret "${{ steps.op-load-secret.outputs.SECRET }}"

