# name: CI
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#   schedule:
#     - cron: 0 8 * * 6
# jobs:
#   test:
#     strategy:
#       matrix:
#         include:
#           - name: macOS
#             os: macos-latest
#             brewfile: macos/brewfile
#             brew_cache_path: |
#               ~/Library/Caches/Homebrew
#               /opt/Homebrew
#               /opt/homebrew/Cellar
#               /opt/homebrew/Caskroom
#             docker_test: false
#       fail-fast: false
#     name: ${{ matrix.name }}
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@v4

#       - name: set up cache
#         uses: actions/cache@v4
#         with:
#           path: ${{ matrix.brew_cache_path }}
#           key: brew-${{ matrix.name }}-${{ hashFiles('**/Brewfile') }}-${{ github.sha }}
#           restore-keys: |
#             brew-${{ matrix.name }}-${{ hashFiles('**/Brewfile') }}-
#             brew-${{ matrix.name }}-

#       - name: create workfolder
#         run: |
#           mkdir -p ~/dotfiles-install-dir
#       - name: install dotfiles
#         run: |
#           HOME=~/dotfiles-install-dir ./install -vv
#       - name: show dotfiles
#         run: |
#           ls -alh ~/dotfiles-install-dir

#       - name: test homebrew installer
#         run: |
#           HOME=~/dotfiles-install-dir installers/homebrew.sh
#       - name: add Homebrew to PATH
#         run: echo "${{ matrix.brewpath }}" >> $GITHUB_PATH
#         if: matrix.brewpath != ''

#       - name: brew cache path
#         run: brew --cache
#       - name: update formulae
#         run: brew update
#       - name: test Brewfile install
#         run: brew bundle --file=${{ matrix.brewfile }} --verbose
#       - name: outdated packages
#         run: brew outdated
#       - name: upgrade packages
#         run: brew upgrade

#       - name: test docker installer
#         run: |
#           HOME=~/dotfiles-install-dir installers/docker.sh
#           sudo docker run hello-world
#         if: matrix.docker_test
